version: 0.1.{build}-{branch}
clone_folder: C:\projects\pandora
platform: x64

for:
  -
    branches:
      only:
        - master
        - /prod.*/
        - /release.*/
    configuration: Release
    environment:
      matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          APPVEYOR_JOB_NAME: windows-msvc2019
          BUILD_DIR: msvc19
          BUILD_TYPE: Release
          COMPILER: MSVC19
          PLATFORM: x64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          APPVEYOR_JOB_NAME: windows-msvc2017
          BUILD_DIR: msvc17
          BUILD_TYPE: Debug
          COMPILER: MSVC17
          PLATFORM: x64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          APPVEYOR_JOB_NAME: windows-mingw64
          BUILD_DIR: mingw64
          BUILD_TYPE: Debug
          COMPILER: MinGW-w64
  -
    branches:
      only:
        - /develop.*/
        - /feat.*/
        - /pandora.*/
    configuration: Debug
    environment:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      APPVEYOR_JOB_NAME: windows-msvc2019
      BUILD_DIR: msvc19
      BUILD_TYPE: Debug
      COMPILER: MSVC19
      PLATFORM: x64

install:
  - git submodule update --init --recursive --remote
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%APPVEYOR_BUILD_FOLDER%\deps\bin;C:\MinGW\bin;%PATH%
  # workaround -> rename sh because its PATH interferes with MinGW's (unfortunately, it will prevent downloading gtest -> no test support for mingw)
  - if [%COMPILER%]==[MinGW-w64] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh_.exe"

build_script:
  - cd C:\projects\pandora
  - mkdir _build
  - cd _build
  - mkdir %BUILD_DIR%
  - cd ..
  # build project
  - if [%COMPILER%]==[MSVC19] cmake -G "Visual Studio 16 2019" -A %PLATFORM% -S . -B ./_build/%BUILD_DIR%
  - if [%COMPILER%]==[MSVC17] cmake -G "Visual Studio 15 2017" -A %PLATFORM% -S . -B ./_build/%BUILD_DIR% -DBUILD_CPP_REVISION="14"
  - if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -S . -B ./_build/%BUILD_DIR% -DCMAKE_C_COMPILER=gcc.exe -DCMAKE_CXX_COMPILER=g++.exe -DCMAKE_MAKE_PROGRAM=mingw32-make.exe
  # compile
  - cmake --build ./_build/%BUILD_DIR% --config %BUILD_TYPE% --target install

test_script:
  - cd C:\projects\pandora\_build\%BUILD_DIR%
  - if [%COMPILER%]==[MSVC19] ctest --output-on-failure
  - if [%COMPILER%]==[MSVC17] ctest --output-on-failure
